# authendication credintials
credentials:
  usernames:
    nimur:
      email: nimur@gmail.com
      name: Nimur Rashid
      password: $2b$12$Vya.5Gw0ur0pDxsjt22/suzsNMS/xXYti30GXZZFQ62nUWwmcLJFm # Placeholder for hashed password of 'abc'

cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - nimur@growwithdata.net



db:
  host: "localhost"
  user: "root"
  passwd: "admin"
  database: "ExpenseDB"
  auth_plugin: "mysql_native_password"

  
email_sender:
  email: "nimur.resource@gmail.com"
  pass: '@&&@+7'